<?php

/**
 * @file
 * Hooks to extend the Readonly Field Widget functionality.
 */

use Drupal\readonly_field_widget\Plugin\Field\FieldWidget\ReadonlyWidget;

/**
 * Implements hook_field_widget_info_alter().
 */
function readonly_field_widget_field_widget_info_alter(&$info) {
  $info['readonly']['field_types'] = ReadonlyWidget::fieldTypes(\Drupal::service('plugin.manager.field.field_type')->getDefinitions());
}
